USE SPJ;
SELECT DISTINCT SNO, JNO FROM SPJ WHERE JNO = "J1"; /* QUESTION 1*/

SELECT DISTINCT SNO, PNO, JNO FROM SPJ WHERE JNO = "J1" AND PNO = "P1"; /*QUESTION 2*/

SELECT DISTINCT SNO, COLOR FROM P, SPJ WHERE SPJ.PNO = P.PNO AND P.COLOR = "红"; /*QUESTION 3*/

SELECT JNO FROM J
WHERE JNO NOT IN   
    (SELECT JNO
    FROM SPJ
    WHERE SNO IN
        (SELECT SNO
        FROM S
        WHERE CITY = '天津')
        AND PNO IN
        (SELECT PNO
        FROM P
        WHERE COLOR = '红')); /*QUESTION 4*/

SELECT DISTINCT JNO FROM SPJ S1
WHERE NOT EXISTS
    (SELECT *
    FROM SPJ S2
    WHERE S2.SNO = 'S1' AND
        NOT EXISTS
            (SELECT *
            FROM SPJ S3
            WHERE S3.JNO = S1.JNO AND S3.PNO = S2.PNO));/* QUESTION 5*/
