USE SPJ;
/* CREATE VIEW V_SPJ(V_SNO, V_PNO, V_QTY)
AS
SELECT SNO, PNO, QTY
FROM SPJ; */

select * from v_spj;
/*QUESTION 1*/
SELECT V_PNO, V_QTY
FROM V_SPJ;

/*QUESTION 2*/
SELECT *
FROM V_SPJ
WHERE V_SNO = 'S1';